### ISSUE TITLE
Can you make a non-callback version?

### ISSUE THREAD

**Issue by itstrath** [gpittarelli/node-ssq#1]
I am making a web based TF2 Pickup website and I have a server pool. I need to make sure the server is on and has less than 5 players in it. So once 12 players have added up, I want to check all the servers in the server pool until I find one that is on and has less than 5 players. Problem is since this is asynchronous and uses a callback, Node continues on before finding and assigning a server.

http://stackoverflow.com/questions/15505438/how-can-i-make-node-wait-or-perhaps-a-different-solution

Sorry for setting this as an issue, I can't find you email or any other way to contact you.

Thanks

**Comment by gpittarelli** [comment]
It looks like you got answers from SO, so I'll go ahead and close this issue. The correct response is that you should avoid synchronous code in most situations with Node.js. Node.js is designed around running in a single thread (not considering things like [cluster](http://nodejs.org/api/cluster.html), so waiting for the response from a remote server query will lock up your whole server until the response completes. Instead, treat asynchronous calls as 'scheduling' a request for data, then craft the callbacks to handle the data and do the next processing work once they have received the data.

Libraries like https://github.com/caolan/async do just this, and provide very nice escape paths from this so-called 'callback hell'. For example:

``` javascript
ssq = require('ssq');
async = require('async');

async.parallel([
  ssq.info.bind('1.2.3.4', 1234),
  ssq.info.bind('ny.redditeast.com', 27015)
  // more servers
], function(err, results) {
  // results in the results array (or an error)
});
```

This becomes very powerful when you start building the array of functions passed to `async.parallel` dynamically.

I hope that clears things up. Feel free to open more issues if you have any more problems with the library.

(As a side note, this library was originally for a tf2lobby replacement also named tf2pickup, though that project never came off the ground because I'm no longer interested in competitive tf2)
