### ISSUE TITLE
Get avatar of players?

### ISSUE THREAD

**Issue by FezVrasta** [gpittarelli/node-ssq#4]
Thanks for the great module!

I'm writing a widget for NodeBB and I'd like to get the avatars of the players logged in my server. Do you know how can I get them?

**Comment by gpittarelli** [comment]
This package can't supply that information for you, because Source servers don't send it. They don't even send player SteamIDs, so you'll have to get the list of SteamIDs on your server in some other way, such as with RCON 'status' command.

Once you have the SteamIDs you can lookup its avatar with the Steam Web API:
http://steamcommunity.com/dev
and specifically this page:
https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0001.29
